apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deepvogue-mlflow
  annotations:
    run.googleapis.com/launch-stage: GA
    run.googleapis.com/ingress: all
    run.googleapis.com/iap: enabled
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: deepvogue-vpc
        run.googleapis.com/vpc-access-egress: private-ranges-only
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      serviceAccountName: mlflow-server-sa@PROJECT_ID.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/PROJECT_ID/deepvogue/mlflow:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
          env:
            - name: MLFLOW_BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: deepvogue-mlflow-db-uri
                  key: latest
            - name: MLFLOW_ARTIFACTS_DESTINATION
              value: gs://deepvogue-mlflow
